DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Aihe CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Ilmoittauminen CASCADE;
DROP TABLE IF EXISTS Oppitunti CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;
DROP TABLE IF EXISTS Tehtava CASCADE;
